spring.application.name=ai-service

server.port=8083

spring.mongodb.uri=mongodb://localhost:27017/fitness_recommendations
spring.mongodb.database=recommendations

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
