server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/recommendations/**
      discovery:
        locator:
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost